apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-log-service
  labels:
    app: activity-log-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: activity-log-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: activity-log-service
    spec:
      containers:
      - name: activity-log-service
        image: ${DOCKER_REGISTRY}/activity-log-service:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: activity-log-config
              key: NODE_ENV
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: activity-log-config
              key: PORT
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: activity-log-secrets
              key: MONGODB_URI
        - name: KAFKA_BROKERS
          valueFrom:
            configMapKeyRef:
              name: activity-log-config
              key: KAFKA_BROKERS
        - name: KAFKA_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: activity-log-config
              key: KAFKA_CLIENT_ID
        - name: KAFKA_CONSUMER_GROUP
          valueFrom:
            configMapKeyRef:
              name: activity-log-config
              key: KAFKA_CONSUMER_GROUP
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: activity-log-config
              key: KAFKA_TOPIC
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: activity-log-config
              key: LOG_LEVEL
        volumeMounts:
        - name: logs
          mountPath: /usr/src/app/logs
      volumes:
      - name: logs
        emptyDir: {} 